apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eddy-python-beam-bridge.fullname" . }}-config
data:
  BOOTSTRAP_SERVER: {{ tpl .Values.kafkaBootstrapServer . | quote }}
  FLINK_HOST: {{ tpl .Values.flinkHost . | quote }}
  FLINK_PORT: {{ .Values.flinkPort | quote }}
  REDIS_HOST: {{ tpl .Values.redisHost . | quote }}

