apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eddy-python-beam-bridge.fullname" . }}
  labels:
    app: {{ include "eddy-python-beam-bridge.name" . }}
    chart: {{ include "eddy-python-beam-bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.podAnnotations }}
  annotations:
    {{- range $key, $value := .Values.podAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "eddy-python-beam-bridge.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "eddy-python-beam-bridge.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: beam-flink-job-server
          image: apache/beam_flink1.12_job_server:2.29.0
          args:
              - "--flink-master={{ include "eddy.fullname" . }}-flink-jobmanager:8081"
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "eddy-python-beam-bridge.fullname" . }}-config
                optional: false
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
              periodSeconds: 60
              exec:
                  command:
                      [
                          'sh',
                          '-c',
                          'celery inspect ping -A app -d celery@$HOSTNAME'
                      ]
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
