{{ if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: {{ include "eddy.fullname" . }}
spec:
  image: docker.io/eddyanalytics/kafka-connect:0.22.0-kafka-2.7.0
  version: {{ .Values.kafka.version | quote }}
  replicas: {{ .Values.kafka.replicas }}
  bootstrapServers: {{ include "eddy.fullname" . }}-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: {{ include "eddy.fullname" . }}-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
{{ end }}

