{{ if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: {{ include "eddy.fullname" . }}
spec:
  replicas: 1
  bootstrapServers: {{ include "eddy.fullname" . }}-kafka-bootstrap:9092
  http:
    port: 8080
{{ end }}